singular_determiners = {
    "eng": {
        "a",
        "some",
        "the",
        "his",
        "her",
        "my",
        "their",
        "this",
        "that",
        "its",
        "our",
        "your",
        "such",
    },
    "fra": {
        "le",
        "la",
        "les",
        "un",
        "une",
        "du",
        "de",
        "de la",
        "ce",
        "cette",
        "mon",
        "ma",
        "ton",
        "ta",
        "son",
        "sa",
        "notre",
        "votre",
        "leur",
        "au",
        "à",
        "l '",
    },
}
