name: ci
on: [push]
jobs:
  ci:
    runs-on: ubuntu-latest
    if: github.ref == 'refs/heads/main'
    steps:
      - uses: actions/checkout@v4
      - name: Install uv
        uses: astral-sh/setup-uv@v5
        with:
          python-version: 3.9
      - name: Install dependencies
        run: uv sync --locked --dev
      - name: Run tests
        run: uv run pytest tests
      - name: Build documentation
        run: |
          source .venv/bin/activate
          cd docs
          make html
          touch _build/html/.nojekyll
      - name: Deploy documentation
        uses: JamesIves/github-pages-deploy-action@v4.2.3
        with:
          branch: gh-pages
          folder: "docs/_build/html"
